spring:
  application:
    name: msa-weather-report-server
  thymeleaf:
    cache: false

eureka:
    # 服务的url
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9994

feign:
  client:
    config:
      feignName:
        connectTimeout: 50000
        readTimeout: 50000
