spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          ## 统一配置的仓库
          uri: https://github.com/MarkGao11520/spring-cloud-microservices-development.git
          ## 仓库路径
          search-paths: config-repo

eureka:
    # 服务的url
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888


